#!/usr/bin/env bash
#accepts an argument and pings that IP address five times
#if there is no argument the displays "Usage: 5-is_the_host..."

if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 $1
fi
