#!/usr/bin/env bash
#displays nums 1->20 and after 4, 9, 17 it displays different strings
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$(( i + 1 ))
done
